apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cdi
  - cert-manager
  - external-secrets
  - gateway-api
  - intel-device-plugins
  - kubevirt
  - metallb
  - node-feature-discovery
  - openebs
  - traefik
  - velero
  - victoria-metrics-operator
