apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: victoria-metrics-grafana-admin
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: victoria-metrics-grafana-admin
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: victoria-metrics-grafana-admin/username
    - secretKey: admin-password
      remoteRef:
        key: victoria-metrics-grafana-admin/password
