apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: victoria-metrics
resources:
  - namespace.yaml
  - operator-repository.yaml
  - repository.yaml
  - grafana-admin-externalsecret.yaml
  - query-auth-externalsecret.yaml
  - operator-release.yaml
  - release.yaml
  - vmauth.yaml
  - vmuser.yaml
  - httproutes.yaml
