apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: victoria-reader
  labels:
    app.kubernetes.io/name: victoria-metrics-query
spec:
  name: victoria-reader
  username: victoria-reader
  passwordRef:
    name: victoria-metrics-query-auth
    key: password
  targetRefs:
    - crd:
        kind: VMCluster/vmselect
        name: victoria-metrics
        namespace: victoria-metrics
      target_path_suffix: /select/0
      paths:
        - /.*
