apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vl-query-auth
  namespace: victoria-metrics
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: vl-query-auth
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: vl-query-auth/username
    - secretKey: password
      remoteRef:
        key: vl-query-auth/password
