apiVersion: operator.victoriametrics.com/v1
kind: VLCluster
metadata:
  name: vl
  namespace: victoria-metrics
spec:
  vlstorage:
    replicaCount: 2
    retentionPeriod: 60d
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/instance: vl
                app.kubernetes.io/name: vlstorage
            topologyKey: kubernetes.io/hostname
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: mayastor-2
          resources:
            requests:
              storage: 100Gi
  vlselect:
    replicaCount: 2
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/instance: vl
                app.kubernetes.io/name: vlselect
            topologyKey: kubernetes.io/hostname
  vlinsert:
    replicaCount: 2
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/instance: vl
                app.kubernetes.io/name: vlinsert
            topologyKey: kubernetes.io/hostname
