apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: vl-query
  namespace: victoria-metrics
spec:
  replicaCount: 1
  userNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: victoria-metrics
  userSelector:
    matchLabels:
      app.kubernetes.io/name: vl-query
