apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets-demo
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: external-secrets-demo
    creationPolicy: Owner
  data:
    - secretKey: message
      remoteRef:
        key: external-secrets-demo/password
