apiVersion: v1
kind: ConfigMap
metadata:
  name: aasa-config
  namespace: aasa
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        location = /.well-known/apple-app-site-association {
            root /usr/share/nginx/html;
            default_type application/json;
        }
    }
  apple-app-site-association: |
    {
      "webcredentials": {
        "apps": [
          "Y3NJQL82R8.uk.co.companyshop.activities",
          "Y3NJQL82R8.uk.co.companyshop.activities.preview"
        ]
      }
    }
