apiVersion: apps/v1
kind: Deployment
metadata:
  name: aasa
  namespace: aasa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aasa
  template:
    metadata:
      labels:
        app: aasa
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: config
              mountPath: /usr/share/nginx/html/.well-known/apple-app-site-association
              subPath: apple-app-site-association
      volumes:
        - name: config
          configMap:
            name: aasa-config
