apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  releaseName: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: "^0.20.0"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
  interval: 1h
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
