apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - namespace.yaml
  - pv-media.yaml
  - pvc-media.yaml
  - pvc-plex-config.yaml
  - service-ifrit.yaml
  - httproutes-ifrit.yaml
  - vm-usenet.yaml
  - pvc-usenet-data.yaml
  - service-usenet-ssh.yaml
  - repository.yaml
  - release.yaml
  - vmrule.yaml
