apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  # Empty string opts out of the default StorageClass (mayastor-1).
  storageClassName: ""
  volumeName: media-nfs
  resources:
    requests:
      storage: 1Ti
