apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: usenet-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: mayastor-2
  resources:
    requests:
      storage: 20Gi
