---
# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: prometheus

    honor_labels: true
    # scrape_interval is defined by the configured global (15s).
    # scrape_timeout is defined by the global default (10s).

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: consul

    consul_sd_configs:
      - server: "consul01:8500"
        # services: ["nginx", "cache", "mysql"] # if omitted all are scraped
        # tags: ["canary", "v1"]
        # node_meta:
        #   rack: "123"
        # allow_stale: true
        # scheme: https
        # tls_config:
        #   ca_file: valid_ca_file
        #   cert_file: valid_cert_file
        #   key_file: valid_key_file
        #   insecure_skip_verify: false

    relabel_configs:
      - source_labels: [__meta_sd_consul_tags]
        separator: ","
        regex: label:([^=]+)=([^,]+)
        target_label: ${1}
        replacement: ${2}
      - source_labels: ['__meta_consul_node']     
        replacement: '$1'
        target_label: instance
      - source_labels: ['__meta_consul_service']
        target_label: job

  # - job_name: docker
  #   docker_sd_configs:
  #     - host: unix:///var/run/docker.sock
