---
- name: Create prometheus config directory
  ansible.builtin.file:
    path: /opt/prometheus
    state: directory
    owner: root
    group: root
    mode: '0644'

- name: Prometheus configuration
  ansible.builtin.copy:
    src: prometheus/prometheus.yml
    dest: /opt/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '0644'

- name: Prometheus container
  community.docker.docker_container:
    name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart_policy: unless-stopped
