apiVersion: v1
kind: Secret
metadata:
    name: sops-demo-secret
stringData:
    demo: ENC[AES256_GCM,data:tV8AcZo56bby7j28aFLiUZ3x,iv:rc+xikp3magS1NUa3vWUctcndclFOtVyCfsKSVamXX8=,tag:F40KpAYzj63eG128teqw+A==,type:str]
sops:
    age:
        - recipient: age1n06sx29zvf6tucsz5prh6dmhs83kkz7ujpxlff7g8n3lj2rxvczs2f8wxy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVlJia3Mya29yME1wNDBW
            eDVRMGVSd2o5NWJtcER0K3RjSG8rcS95VXdJCk9TZTBOOWtmZmVNbXdSMWxmRUFQ
            a1p3WjZTamNtZnlWT3ZuOUhiRVExVUUKLS0tIFVtOHl0eUNrQ0N2amZnUnJ0OHZI
            ZHY5WjR5cXF2NHRwUWNud3pUYXZISlUKbxmgT0ycYgKcQjxjMF0y6irHInFo9puC
            GEKKS/PQqrr3hI3aNV+7JUmRDTRylFlcZerzjnOv5mI35gTRhsZrOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-12T02:12:57Z"
    mac: ENC[AES256_GCM,data:NPoVuK88bp7wd2NFUCH2ywuQSviMw5ZH+sJ8r/CzsqAP3jDBOcIP2gLmQylsLD6K9P9SiEJDv8DCj5bthn0APz0v7JndoQV/48qwpg0gZO/J9pkHWwgbayrlJBtKCtUVbjIr23dtss4Ke21W+ppgN4uPK77f5KeIV3t0p+qlsog=,iv:LX17sMk3qeCVq0CEQ9OzwP+/7BxPvSHLOif63cjbd9c=,tag:/mcw+gQ/u9V3rv1E4jzFEw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
