---
# API and dashboard configuration
api:
  insecure: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: ":443"

providers:
  consulCatalog:
    endpoint:
      address: consul01:8500
    prefix: traefik

certificatesResolvers:
  letsencrypt:
    acme:
      email: jxhughes95@gmail.com
      storage: acme.json
      dnsChallenge:
        resolvers:
          - "8.8.8.8:53"
        provider: route53
