---
machine:
  sysctls:
    vm.nr_hugepages: "1024"
  network:
    $patch: delete
  features:
    stableHostname:
      $patch: delete
    rbac: true
    apidCheckExtKeyUsage: true
  nodeLabels:
    openebs.io/engine: mayastor
  kubelet:
    extraMounts:
      - destination: /var/local
        type: bind
        source: /var/local
        options:
          - bind
          - rshared
          - rw
