apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: openebs-io-engine
  namespace: openebs
  labels:
    app.kubernetes.io/part-of: openebs
    app.kubernetes.io/component: monitoring
spec:
  jobLabel: app
  namespaceSelector:
    matchNames:
      - openebs
  selector:
    matchLabels:
      app: io-engine
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 5m
