---
apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  url: https://prometheus.svc.lan.jhcloud.io
  access: proxy
  isDefault: true
- name: Loki
  type: loki
  url: https://loki.svc.lan.jhcloud.io
