apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vm-grafana-admin
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: vm-grafana-admin
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: vm-grafana-admin/username
    - secretKey: admin-password
      remoteRef:
        key: vm-grafana-admin/password
