apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: victoria-metrics
resources:
  - repository.yaml
  - grafana-admin-externalsecret.yaml
  - query-auth-externalsecret.yaml
  - release.yaml
  - httproutes.yaml
  - vmservicescrape.yaml
  - vmauth.yaml
  - vmuser.yaml
