apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vm
  namespace: victoria-metrics
spec:
  releaseName: vm
  dependsOn:
    - name: vm-operator
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: "0.72.4"
      sourceRef:
        kind: HelmRepository
        name: vm
  interval: 24h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: vm-kube-state-metrics-flux-values
      valuesKey: values.yaml
  values:
    fullnameOverride: vm
    victoria-metrics-operator:
      enabled: false
      crds:
        cleanup:
          enabled: false
    defaultDashboards:
      enabled: true
    defaultDatasources:
      extra:
        - name: VictoriaLogs
          type: victoriametrics-logs-datasource
          access: proxy
          url: http://vlselect-vl.victoria-metrics.svc:9471
          uid: VictoriaLogs
          version: 1
          orgId: 1
          isDefault: false
          editable: false
    defaultRules:
      create: true
      rules:
        Watchdog:
          create: false
    grafana:
      enabled: true
      admin:
        existingSecret: vm-grafana-admin
        userKey: admin-user
        passwordKey: admin-password
      plugins:
        - victoriametrics-logs-datasource
      deploymentStrategy:
        type: Recreate
      ingress:
        enabled: false
      persistence:
        enabled: true
        type: pvc
        accessModes:
          - ReadWriteOnce
        storageClassName: mayastor-3
        size: 20Gi
      grafana.ini:
        server:
          domain: grafana.ducknet.io
          root_url: https://grafana.ducknet.io
    alertmanager:
      enabled: true
      route:
        enabled: false
      useManagedConfig: true
      config:
        route:
          receiver: pushover
          routes:
            - matchers:
                - alertname = InfoInhibitor
              receiver: blackhole
        receivers:
          - name: blackhole
          - name: pushover
            pushover_configs:
              - token:
                  name: pushover-credentials
                  key: vmalert_token
                user_key:
                  name: pushover-credentials
                  key: user_key
                send_resolved: true
        inhibit_rules:
          - source_matchers:
              - alertname = InfoInhibitor
            target_matchers:
              - severity = info
            equal:
              - namespace
      spec:
        externalURL: https://alerts.ducknet.io
        replicaCount: 1
        storage:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              storageClassName: mayastor-3
              resources:
                requests:
                  storage: 20Gi
    vmauth:
      enabled: false
    vmsingle:
      enabled: false
    vmagent:
      enabled: true
      spec:
        replicaCount: 1
    vmalert:
      enabled: true
      spec:
        replicaCount: 1
    vmcluster:
      enabled: true
      spec:
        replicationFactor: 1
        retentionPeriod: 90d
        vmstorage:
          replicaCount: 3
          storage:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                storageClassName: mayastor-3
                resources:
                  requests:
                    storage: 50Gi
        vmselect:
          replicaCount: 2
          storage:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                storageClassName: mayastor-3
                resources:
                  requests:
                    storage: 2Gi
        vminsert:
          replicaCount: 2
    prometheus-node-exporter:
      enabled: false
    kube-state-metrics:
      enabled: true
    kubeApiServer:
      enabled: true
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeEtcd:
      enabled: false
    kubelet:
      enabled: true
    kubeProxy:
      enabled: false
