---
- hosts: all
  roles:
  - role: ansible-role-firewalld
  - role: geerlingguy.repo-epel
    when: ansible_facts['distribution'] != "Fedora"
  - role: cloudalchemy.node_exporter

  tasks:
  - name: Add my user account
    user:
      name: jhughes
      shell: /bin/bash
      groups: wheel
      append: yes

  - name: Add key for jhughes user
    authorized_key:
      user: jhughes
      state: present
      key: https://github.com/jhughes01.keys
