---
- hosts: all
  roles:
  - ansible-role-firewalld
  # - geerlingguy.repo-epel # Doesn't work with Fedora
  - cloudalchemy.node_exporter

  tasks:
  - name: Add my user account
    user:
      name: jhughes
      shell: /bin/bash
      groups: wheel
      append: yes

  - name: Add key for jhughes user
    authorized_key:
      user: jhughes
      state: present
      key: https://github.com/jhughes01.keys
