---
- hosts: consul_instances
  roles:
  - ansible-consul
  vars:
    consul_version: 1.10.1
    consul_datacenter: homelab
    # consul_install_upgrade: true
    # consul_bootstrap_expect: true
    consul_client_address: 0.0.0.0
    consul_dnsmasq_enable: true
    consul_dnsmasq_servers: 
      - 192.168.1.1
