---
- hosts: consul_instances
  roles:
  - ansible-consul
  vars:
    consul_version: 1.17.1
    consul_enable_local_script_checks: true
    consul_datacenter: homelab
    consul_install_upgrade: true
    consul_bootstrap_expect: true
    consul_client_address: 0.0.0.0
    consul_dnsmasq_enable: true
    consul_dnsmasq_servers: 
      - 192.168.1.1
    consul_services: "{{ common_consul_catalog_services | union(consul_catalog_services | default([])) }}"

  tasks:
    - name: Ensure NetworkManager configured to lookup using dnsmasq
      ansible.builtin.copy:
        src: "dns.conf"
        dest: "/etc/NetworkManager/conf.d/dns.conf"
        owner: root
        group: root
        mode: '0644'
      register: dns_conf

    - name: Reload NetworkManager config
      ansible.builtin.command: nmcli general reload
      when: dns_conf.changed
