---
- hosts: docker
  # Deprecation notice fix but option not yet available on latest ansible?
  # module_defaults:
  #   community.docker.docker_container:
  #     container_default_behaviour: no_defaults

  pre_tasks:
  - name: Install packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - python3
      - nfs-utils

  - name: Mount plex media
    ansible.posix.mount:
      src: storage:/volume1/plex-media/
      path: /data/plex-media
      opts: auto,rw,noatime,nolock,bg,soft
      state: mounted
      fstype: nfs
  
  roles:
  - geerlingguy.docker
  - geerlingguy.pip
  vars:
    docker_edition: 'ce'
    docker_packages: 
      - docker-ce
      - docker-ce-cli
      - docker-ce-rootless-extras
      - containerd.io
    docker_install_compose_plugin: true
    pip_install_packages:
    - name: docker
    - name: docker-compose

  tasks:
    - name: consul exporter container
      include_tasks: docker-services/consul-exporter.yml

    - name: grafana container
      include_tasks: docker-services/grafana.yml

    - name: media stack
      include_tasks: docker-services/media.yml

    - name: prometheus container
      include_tasks: docker-services/prometheus.yml

    - name: traefik container
      include_tasks: docker-services/traefik.yml

    - name: unifi-poller
      include_tasks: docker-services/unifi-poller.yml

    - name: alertmanager
      include_tasks: docker-services/alertmanager.yml

    - name: exportarr
      include_tasks: docker-services/exportarr.yml
