---
- hosts: kubernetes
  pre_tasks:
    - name: Add br_netfilter module
      community.general.modprobe:
        name: br_netfilter
        state: present
    # - name: update kernel settings
    #   become: yes
    #   sysctl:
    #     name: net.ipv4.ip_forward
    #     value: 1
    #     sysctl_set: yes
    #     state: present
    #     reload: yes
    - name: remove swap generator
      ansible.builtin.package:
        name: zram-generator
        state: absent
      register: swap
    - name: disable swap
      ansible.builtin.command: "swapoff -a"
      when: swap.changed
  roles:
    - geerlingguy.containerd
    - geerlingguy.kubernetes
  vars:
    # kubernetes_version: '1.25'
    kubernetes_allow_pods_on_master: false
    kubernetes_config_kubelet_configuration:
      cgroupDriver: systemd
    kubernetes_config_init_configuration:
      localAPIEndpoint:
        advertiseAddress: "{{ kubernetes_apiserver_advertise_address | default(ansible_default_ipv4.address, true) }}"
    kubernetes_config_cluster_configuration:
      networking:
        podSubnet: "{{ kubernetes_pod_network.cidr }}"
      kubernetesVersion: "{{ kubernetes_version_kubeadm }}"
    kubernetes_apiserver_advertise_address: ''
    kubernetes_version_kubeadm: 'stable-{{ kubernetes_version }}'
    kubernetes_ignore_preflight_errors: 'all'
