---
- hosts: libvirt_hosts
  roles:
    - ansible-role-libvirt

  pre_tasks:
  # More hassle than it's worth managing this in Ansible due to connection drops partway

  # - name: Create bridge interface
  #   nmcli:
  #     conn_name: br0
  #     state: present
  #     type: bridge
  #     stp: no
  #     autoconnect: yes

  # - name: Remove default interface
  #   nmcli:
  #     conn_name: enp39s0
  #     state: absent
  #   when: todo: wrap in conditional

  # - name: Add bridge slave
  #   nmcli:
  #     conn_name: enp39s0
  #     state: present
  #     type: bridge-slave
  #     master: br0
  #     autoconnect: yes
  #   notify:
  #     - restart networkmanager

  tasks:
  - name: Enable libvirt group access to unix socket
    lineinfile:
      dest: /etc/libvirt/libvirtd.conf
      regexp: "^#unix_sock_group"
      line: 'unix_sock_group = "libvirt"'
      state: present
    notify:
      - restart libvirtd

  - name: Set libvirt unix socket permissions
    lineinfile:
      dest: /etc/libvirt/libvirtd.conf
      regexp: "^#unix_sock_rw_perms"
      line: 'unix_sock_rw_perms = "0770"'
      state: present
    notify:
      - restart libvirtd

  handlers:
    - name: restart libvirtd
      ansible.builtin.service:
        name: libvirtd
        state: restarted

    - name: restart networkmanager
      ansible.builtin.service:
        name: NetworkManager
        state: restarted
