---
- hosts: plex

  pre_tasks:
  - name: Install packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - nfs-utils

  - name: Mount plex config
    ansible.posix.mount:
      src: storage:/volume1/plex-config
      path: /var/lib/plexmediaserver/
      opts: auto,rw,noatime,nolock,bg,soft
      state: absent
      fstype: nfs

  - name: Mount plex data
    ansible.posix.mount:
      src: storage:/volume1/plex-media/
      path: /data/plex-media
      opts: auto,rw,noatime,nolock,bg,soft
      state: mounted
      fstype: nfs

  roles:
  - ansible-role-plex
