apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-rpc-secret
  namespace: garage
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: garage-rpc-secret
    creationPolicy: Owner
  data:
    - secretKey: rpcSecret
      remoteRef:
        key: garage/rpc-secret
