{
 "title": "UniFi-Poller: UAP Insights",
 "description": "UniFi Poller v2.0.1 Displays detailed information for wireless access points in a UniFi network using Prometheus.",
 "tags": [
  "unifi",
  "uap",
  "unifi-poller"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Controller",
    "query": {
     "query": "label_values(unifipoller_device_info{type=\"uap\"},source)"
    }
   },
   {
    "name": "Site",
    "query": {
     "query": "label_values(unifipoller_device_info{source=~\"$Controller\", type=\"uap\"},site_name)"
    }
   },
   {
    "name": "AP",
    "label": "UniFi AP:",
    "query": {
     "query": "label_values(unifipoller_device_info{site_name=~\"$Site\", type=~\"uap|udm\",model!=\"UDMPRO\"},name)"
    }
   },
   { "name": "Smooth", "query": "30s,1m,2m,5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<br>\n<br>\n<center><b><font size=\"6px\">Unifi UAP</font></b></center>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Clients / Channel",
   "type": "grafana-piechart-panel",
   "description": "Visualize wireless channel usage w/ wired client counts.",
   "gridPos": { "h": 10, "w": 6, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (channel) (unifipoller_client_roam_count_total{site_name=~\"$Site\", ap_name=~\"$AP\"})\n",
     "legendFormat": "Ch {{channel}}"
    }
   ]
  },
  {
   "title": "Clients / AP Radio",
   "type": "grafana-piechart-panel",
   "description": "Visualize how many clients are connected to which radios/APs.",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (radio_desc) (unifipoller_client_uptime_seconds{site_name=~\"$Site\", ap_name=~\"$AP\"})",
     "legendFormat": "{{radio_desc}}"
    }
   ]
  },
  {
   "title": "Client / MAC OUI",
   "type": "grafana-piechart-panel",
   "description": "This shows an OUI breakdown from Unifi's perspective.",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (oui) (unifipoller_client_uptime_seconds{site_name=~\"$Site\", ap_name=~\"$AP\"})",
     "legendFormat": "e {{oui}}"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(unifipoller_device_stations{site_name=~\"$Site\", name=~\"$AP\", station_type=\"user\"})"
    }
   ]
  },
  {
   "title": "Guests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(unifipoller_device_stations{site_name=~\"$Site\", name=~\"$AP\", station_type=\"guest\"})"
    }
   ]
  },
  {
   "title": "Now",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Access Point Details",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (ip,mac,model,name,serial,site_name,type,version) (unifipoller_device_info{site_name=~\"$Site\", name=~\"$AP\"})"
    },
    {
     "expr": "sum by (ip,mac,model,name,serial,site_name,type,version) (unifipoller_device_uptime_seconds{site_name=~\"$Site\", name=~\"$AP\"})"
    },
    {
     "expr": "sum by (ip,mac,model,name,serial,site_name,type,version) (unifipoller_device_bytes_total{site_name=~\"$Site\", name=~\"$AP\"})"
    }
   ]
  },
  {
   "title": "Networks / UAP",
   "type": "table-old",
   "description": "The counters in this table represent uptime totals and do not change with the time range selector. ",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_ccq_ratio{site_name=~\"$Site\", name=~\"$AP\"})"
    },
    {
     "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_average_client_signal{site_name=~\"$Site\", name=~\"$AP\"})"
    },
    {
     "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_receive_dropped_total{site_name=~\"$Site\", name=~\"$AP\"}) "
    },
    {
     "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_transmit_dropped_total{site_name=~\"$Site\", name=~\"$AP\"}) "
    },
    {
     "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_transmit_bytes_total{site_name=~\"$Site\", name=~\"$AP\"}) "
    },
    {
     "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_receive_bytes_total{site_name=~\"$Site\", name=~\"$AP\"}) "
    },
    {
     "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_receive_packets_total{site_name=~\"$Site\", name=~\"$AP\"}) "
    },
    {
     "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_transmit_packets_total{site_name=~\"$Site\", name=~\"$AP\"}) "
    }
   ]
  },
  {
   "title": "UAP CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "expr": "unifipoller_device_cpu_utilization_ratio{site_name=~\"$Site\",name=~\"$AP\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "UAP Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "percentunit", "label": "Memory Utilization" }
   ],
   "targets": [
    {
     "expr": "unifipoller_device_memory_utilization_ratio{site_name=~\"$Site\",name=~\"$AP\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "UAP Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "unifipoller_device_load_average_1{site_name=~\"$Site\",name=~\"$AP\"}",
     "legendFormat": "{{name}} load1"
    },
    {
     "expr": "unifipoller_device_load_average_15{site_name=~\"$Site\",name=~\"$AP\"}",
     "legendFormat": "{{name}} load15"
    }
   ]
  },
  {
   "title": "Clients / UAP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "unifipoller_device_stations{site_name=~\"$Site\",name=~\"$AP\"}",
     "legendFormat": "{{name}} users"
    }
   ]
  },
  {
   "title": "Wireless Traffic / Vendor",
   "type": "graph",
   "description": "Devices TX / RX bytes per second grouped by OUI. RX on negative axis.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum (unifipoller_client_receive_rate_bytes{site_name=~\"$Site\",ap_name=~\"$AP\"}) by (oui)",
     "legendFormat": "{{oui}} Rx"
    },
    {
     "expr": "sum (unifipoller_client_transmit_rate_bytes{site_name=~\"$Site\",ap_name=~\"$AP\"}) by (oui)",
     "legendFormat": "{{oui}} Tx"
    }
   ]
  },
  {
   "title": "Users & Guests / Radio Band",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (unifipoller_device_radio_stations{radio=\"ng\", site_name=~\"$Site\",name=~\"$AP\", station_type=\"guest\"}) by  (radio,name)",
     "legendFormat": "{{name}} Guests 2,4GHz"
    },
    {
     "expr": "sum (unifipoller_device_radio_stations{radio=\"ng\", site_name=~\"$Site\",name=~\"$AP\", station_type=\"user\"}) by (radio,name)",
     "legendFormat": "{{name}} Users  2.4GHz"
    },
    {
     "expr": "sum (unifipoller_device_radio_stations{radio=\"na\", site_name=~\"$Site\",name=~\"$AP\", station_type=\"user\"}) by (radio,name)",
     "legendFormat": "{{name}} Users 5GHz"
    },
    {
     "expr": "sum (unifipoller_device_radio_stations{radio=\"na\", site_name=~\"$Site\",name=~\"$AP\", station_type=\"guest\"}) by (radio,name)",
     "legendFormat": "{{name}} Guests 5GHz"
    }
   ]
  },
  {
   "title": "Average AP Client Signal",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "dBm", "label": "Average Client Signal" }
   ],
   "targets": [
    {
     "expr": "unifipoller_device_vap_average_client_signal{name=~\"$AP\"}",
     "legendFormat": "{{name}} {{vap_name}} {{radio}}"
    }
   ]
  },
  {
   "title": "Average AP Client RSSI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "dBm", "label": "Average Client RSSI" }
   ],
   "targets": [
    {
     "expr": "avg(unifipoller_client_rssi_db{ap_name=~\"$AP\"}) by (ap_name, radio_name)",
     "legendFormat": "{{ap_name}}  {{radio_name}}"
    }
   ]
  },
  {
   "title": "5 GHz Client Connection Quality",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "percentunit", "label": "Average CCQ % / VAP" }
   ],
   "targets": [
    {
     "expr": "unifipoller_device_vap_ccq_ratio{site_name=~\"$Site\",name=~\"$AP\", radio=\"na\"}",
     "legendFormat": "{{name}} {{vap_name}}"
    }
   ]
  },
  {
   "title": "2.4 GHz Client Connection Quality",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "percentunit", "label": "Average CCQ % / VAP" }
   ],
   "targets": [
    {
     "expr": "unifipoller_device_vap_ccq_ratio{site_name=~\"$Site\",name=~\"$AP\", radio=\"ng\"}",
     "legendFormat": "{{name}} {{vap_name}}"
    }
   ]
  },
  {
   "title": "5 GHz Channel Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "unifipoller_device_radio_channel_utilization_receive_ratio{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}",
     "legendFormat": "{{name}} Rx"
    },
    {
     "expr": "unifipoller_device_radio_channel_utilization_transmit_ratio{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}",
     "legendFormat": "{{name}} Tx"
    }
   ]
  },
  {
   "title": "2.4 GHz Channel Utilization",
   "type": "graph",
   "description": "Displays 2.4GHz usage.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "unifipoller_device_radio_channel_utilization_receive_ratio{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}",
     "legendFormat": "{{name}} {{radio}} Rx"
    },
    {
     "expr": "unifipoller_device_radio_channel_utilization_transmit_ratio{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}",
     "legendFormat": "{{name}} {{radio}} Tx"
    }
   ]
  },
  {
   "title": "5 GHz Traffic",
   "type": "graph",
   "description": "RX is on the negative Axis.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(unifipoller_device_vap_transmit_bytes_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[5m])) by (name)",
     "legendFormat": "{{name}} Tx"
    },
    {
     "expr": "sum (rate(unifipoller_device_vap_receive_bytes_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[5m])) by (name)",
     "legendFormat": "{{name}}  Rx"
    }
   ]
  },
  {
   "title": "2.4 GHz Traffic",
   "type": "graph",
   "description": "RX is on the negative Axis.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(unifipoller_device_vap_transmit_bytes_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[5m])) by (name)",
     "legendFormat": "{{name}} Tx"
    },
    {
     "expr": "sum (rate(unifipoller_device_vap_receive_bytes_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[5m])) by (name)",
     "legendFormat": "{{name}} Rx"
    }
   ]
  },
  {
   "title": "5 GHz Packets",
   "type": "graph",
   "description": "PPS on the na band. In is on the negative Axis.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "pps", "label": "PPS" }
   ],
   "targets": [
    {
     "expr": "sum (rate(unifipoller_device_vap_transmit_packets_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Out"
    },
    {
     "expr": "sum (rate(unifipoller_device_vap_receive_packets_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} In"
    }
   ]
  },
  {
   "title": "2.4 GHz Packets",
   "type": "graph",
   "description": "PPS on the ng band calculated in 30 second buckets. In is on the negative Axis.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "pps", "label": "PPS" }
   ],
   "targets": [
    {
     "expr": "sum (rate(unifipoller_device_vap_transmit_packets_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Out"
    },
    {
     "expr": "sum (rate(unifipoller_device_vap_receive_packets_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} In"
    }
   ]
  },
  {
   "title": "5 GHz Drops/Errors",
   "type": "graph",
   "description": "Visualize packet errors (several types)  per second in the 5GHz band.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(unifipoller_device_vap_receive_dropped_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Drops Rx"
    },
    {
     "expr": "sum (rate(unifipoller_device_vap_transmit_dropped_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Drops Tx"
    },
    {
     "expr": "sum (rate(unifipoller_device_vap_receive_errors_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Errors Rx"
    },
    {
     "expr": "sum (rate(unifipoller_device_vap_transmit_errors_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Errors Tx"
    },
    {
     "expr": "sum (rate(unifipoller_device_vap_receive_crypts_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Crypts Rx"
    },
    {
     "expr": "sum (rate(unifipoller_device_vap_receive_frags_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Frags Rx"
    },
    {
     "expr": "sum (rate(unifipoller_device_vap_receive_nwids_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Nwids Rx"
    },
    {
     "expr": "sum (rate(unifipoller_device_vap_transmit_retries_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Retries Tx"
    }
   ]
  },
  {
   "title": "2.4 GHz Drops/Errors",
   "type": "graph",
   "description": "In is on the negative axis.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(unifipoller_device_vap_receive_dropped_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Drops Rx"
    },
    {
     "expr": "sum (rate(unifipoller_device_vap_transmit_dropped_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Drops Tx"
    },
    {
     "expr": "sum (rate(unifipoller_device_vap_receive_errors_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Errors Rx"
    },
    {
     "expr": "sum (rate(unifipoller_device_vap_transmit_errors_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Errors Tx"
    },
    {
     "expr": "sum (rate(unifipoller_device_vap_receive_crypts_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Crypts Rx"
    },
    {
     "expr": "sum (rate(unifipoller_device_vap_receive_frags_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Frags Rx"
    },
    {
     "expr": "sum (rate(unifipoller_device_vap_receive_nwids_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Nwids Rx"
    },
    {
     "expr": "sum (rate(unifipoller_device_vap_transmit_retries_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} Retries Tx"
    }
   ]
  }
 ]
}