apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: node-exporter
  namespace: node-exporter
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - node-exporter
  selector:
    matchLabels:
      app.kubernetes.io/instance: node-exporter
      app.kubernetes.io/name: prometheus-node-exporter
  endpoints:
    - port: metrics
      interval: 30s
      metricRelabelConfigs:
        - action: drop
          regex: /var/lib/kubelet/pods.+
          source_labels:
            - mountpoint
