apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: vm-admin
  namespace: victoria-metrics
  labels:
    app.kubernetes.io/name: vm-query
spec:
  name: vm-admin
  username: admin
  passwordRef:
    name: vm-query-auth
    key: password
  targetRefs:
    - crd:
        kind: VMCluster/vmselect
        name: vm
        namespace: victoria-metrics
      target_path_suffix: /select/0/prometheus
      paths:
        - /.*
