---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-store
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: platform
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/platform/base/external-secrets-store
  prune: true
  wait: true
  timeout: 5m0s
