---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: metallb # Depends on MetalLB
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/platform/base/ingress-nginx
  prune: true
  wait: true
  timeout: 5m0s
