---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: platform # Depends on CRDs created by MetalLB Helm Release
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/platform/base/metallb-config
  prune: true
  wait: true
  timeout: 5m0s
