---
- name: Consul exporter container
  community.docker.docker_container:
    name: consul-exporter
    image: prom/consul-exporter
    ports:
      - 9107:9107
    dns_servers:
      - "192.168.1.1"
    command: "--consul.server=https://consul-ui.svc.ducknet.io"
    restart_policy: unless-stopped
