---
- name: Create traefik config directory
  ansible.builtin.file:
    path: /opt/traefik
    state: directory
    owner: root
    group: root
    mode: "0644"

- name: Traefik configuration
  ansible.builtin.copy:
    src: traefik/traefik.yml
    dest: /opt/traefik/traefik.yml
    owner: root
    group: root
    mode: "0644"
  register: traefik_config

- name: Traefik container
  community.docker.docker_container:
    name: traefik
    image: traefik:v3.5.3
    ports:
      - 80:80 # http
      - 443:443 # https
      - 8080:8080 # traefik dashboard
    dns_servers:
      - "192.168.1.1"
    volumes:
      - /opt/traefik/traefik.yml:/etc/traefik/traefik.yml
    restart_policy: unless-stopped
    restart: "{{ traefik_config.changed }}"
    env:
      CLOUDFLARE_DNS_API_TOKEN: "{{ cloudflare_dns_api_token }}"
      CLOUDFLARE_EMAIL: "{{ cloudflare_email }}"
