apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: healthchecks-io-ping
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: healthchecks-io-ping
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: healthchecks-io-ping/url
