---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform
  namespace: flux-system
spec:
  interval: 3m
  # dependsOn:
  #   - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/platform/dev
  prune: true
  wait: true
  timeout: 5m0s
