---
cluster:
  etcd:
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: etcd-metrics-ingress
portSelector:
  ports:
    - 2381
  protocol: tcp
ingress:
  # Flannel SNATs pod-to-node traffic to the source node IP on this cluster.
  - subnet: 192.168.1.25/32
  - subnet: 192.168.1.26/32
  - subnet: 192.168.1.27/32
