---
- hosts: kafka
  roles:
  - geerlingguy.java
  - ansible-role-kafka
  - kafka_exporter-ansible-role
  vars:
    java_packages: 
      - java-17-openjdk
    # java_home: "/etc/java/java-17-openjdk"
