---
name: metal

on:
  pull_request:
    paths:
      - infra/metal/**
      - scripts/check-schematic.sh
      - scripts/check-talos-version.sh
      - .github/workflows/metal.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  schematic:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - run: ./scripts/check-schematic.sh

      - run: ./scripts/check-talos-version.sh
